global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'supportrag-api'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['rag-app:8000']
